### ISSUE TITLE
cannot find protocol declaration for 'GIDSignInUIDelegate'; did you mean 'GIDSignInDelegate

### ISSUE THREAD

**Issue by TWBestATM** [googlesamples/google-signin-unity#102]
▸ ❌;  /BUILD_PATH/gamewolfinc.testslots.release_ios/temp.XXXXXX20190816-5373-lqln/Libraries/Plugins/IOS/GoogleSignIn/GoogleSignIn.h:18:36: cannot find protocol declaration for 'GIDSignInUIDelegate'; did you mean 'GIDSignInDelegate'?
8124: ▸ ❌;  /BUILD_PATH/gamewolfinc.testslots.release_ios/temp.XXXXXX20190816-5373-lqln/Libraries/Plugins/IOS/GoogleSignIn/GoogleSignInAppController.mm:78:10: property 'uiDelegate' not found on object of type 'GIDSignIn *'; did you mean 'delegate'?
8125: ▸ ❌;  /BUILD_PATH/gamewolfinc.testslots.release_ios/temp.XXXXXX20190816-5373-lqln/Libraries/Plugins/IOS/GoogleSignIn/GoogleSignInAppController.mm:99:38: no visible @interface for 'GIDSignIn' declares the selector 'handleURL:sourceApplication:annotation:'
8126: ▸ ❌;  /BUILD_PATH/gamewolfinc.testslots.release_ios/temp.XXXXXX20190816-5373-lqln/Libraries/Plugins/IOS/GoogleSignIn/GoogleSignInAppController.mm:116:22: no visible @interface for 'GIDSignIn' declares the selector 'handleURL:sourceApplication:annotation:

I get this error
how can I fix that?
can someone help?
is they replace name or other?

**Comment by kevinfoley** [comment]
T y p I n g   l I k e  t h I s  m a k e s  y o u r  m e s s a g e  v e r y  d I f f I c u l t  t o  r e a d.

I am having this same issue.

**Comment by kevinfoley** [comment]
Why would you write your message like that? It's so difficult to read.

I am experiencing the same issue. Possibly related: https://github.com/react-native-community/react-native-google-signin/issues/707

**Comment by TWBestATM** [comment]
> Why would you write your message like that? It's so difficult to read.
> 
> I am experiencing the same issue. Possibly related: [react-native-community/react-native-google-signin#707](https://github.com/react-native-community/react-native-google-signin/issues/707)
I fix my message . It's easy to read

**Comment by Kromzem** [comment]
I was having the same error and by looking at my Podfile I now know why:

https://developers.google.com/identity/sign-in/ios/release 
They renamed something and the Podfile was taking every version above 4.0.2 (">=4.0.2").

So a simple fix is to change the version to be always below 5.0.0.

Either you change it in your Podfile directly:
**"pod 'GoogleSignIn', '>= 4.0.2'"** to **"pod 'GoogleSignIn', '< 5.0.0'"**

or you change it in the GoogleSignInDependencies.xml (for future rebuilds of the XCode proj.):
File: **/Assets/GoogleSignIn/Editor/GoogleSignInDependencies.xml**
**"<iosPod name="GoogleSignIn" version=">=4.0.2" ...>"** to 
**"<iosPod name="GoogleSignIn" version="< 5.0.0" ...>"**

**Comment by TWBestATM** [comment]
> I was having the same error and by looking at my Podfile I now know why:
> 
> https://developers.google.com/identity/sign-in/ios/release
> They renamed something and the Podfile was taking every version above 4.0.2 (">=4.0.2").
> 
> So a simple fix is to change the version to be always below 5.0.0.
> 
> Either you change it in your Podfile directly:
> **"pod 'GoogleSignIn', '>= 4.0.2'"** to **"pod 'GoogleSignIn', '< 5.0.0'"**
> 
> or you change it in the GoogleSignInDependencies.xml (for future rebuilds of the XCode proj.):
> File: **/Assets/GoogleSignIn/Editor/GoogleSignInDependencies.xml**
> **"<iosPod name="GoogleSignIn" version=">=4.0.2" ...>"** to
> **"<iosPod name="GoogleSignIn" version="< 5.0.0" ...>"**
Thx 
this is work
they change somename in googlesignin 5.0.0

**Comment by ottolb** [comment]
hi, @Kromzem solution worked for me on local builds, on the cloud build the XML parser throws an error when using the '<' 5.0.0 
Perhaps using an escape might solve, temporarily I just set to = 5.0.0 and cloud build worked fine

**Comment by mklitsner** [comment]
Thanks this worked for me!

**Comment by fpbolivar** [comment]
Same problem here!!!
<img width="626" alt="Screen Shot 2019-08-25 at 12 43 02 AM" src="https://user-images.githubusercontent.com/44249178/63645661-5818de00-c6d1-11e9-8048-21a529b8b66e.png">

**Comment by fpbolivar** [comment]
still without answer I tried changing 4.0.2 to 5 and still not working for me

**Comment by TWBestATM** [comment]
> still without answer I tried changing 4.0.2 to 5 and still not working for me

you need to change >= to< . it will work when version less than 5

**Comment by TWBestATM** [comment]
> hi, @Kromzem solution worked for me on local builds, on the cloud build the XML parser throws an error when using the '<' 5.0.0
> Perhaps using an escape might solve, temporarily I just set to = 5.0.0 and cloud build worked fine
try"& lt;" (no cantain space and "")   replease  '<'  . it can solve xml error

**Comment by TWBestATM** [comment]
> > hi, @Kromzem solution worked for me on local builds, on the cloud build the XML parser throws an error when using the '<' 5.0.0
> > Perhaps using an escape might solve, temporarily I just set to = 5.0.0 and cloud build worked fine
> > try"& lt;"  change <  . it can solve xml error

**Comment by fpbolivar** [comment]
@TWBestATM  i did that and still without working :c

**Comment by TWBestATM** [comment]
> @TWBestATM i did that and still without working :c

which erro you get?

**Comment by fpbolivar** [comment]
> Same problem here!!!
> <img alt="Screen Shot 2019-08-25 at 12 43 02 AM" width="626" src="https://user-images.githubusercontent.com/44249178/63645661-5818de00-c6d1-11e9-8048-21a529b8b66e.png">

those ones

@TWBestATM

**Comment by TWBestATM** [comment]
> > Same problem here!!!
> > <img alt="Screen Shot 2019-08-25 at 12 43 02 AM" width="626" src="https://user-images.githubusercontent.com/44249178/63645661-5818de00-c6d1-11e9-8048-21a529b8b66e.png">
> 
> those ones
> 
> @TWBestATM

can i see your setting about iospod?

**Comment by fpbolivar** [comment]
@TWBestATM im new with cocoa how can i do that?

**Comment by TWBestATM** [comment]
> @TWBestATM im new with cocoa how can i do that?

what do you mean?
it's mean cocoapod?
if it is .it should work as well

**Comment by fpbolivar** [comment]
i mean  how can i show you my settings about iospod? @TWBestATM

**Comment by TWBestATM** [comment]
> i mean how can i show you my settings about iospod? @TWBestATM
show me you file in
File: /Assets/GoogleSignIn/Editor/GoogleSignInDependencies.xml
and try replease
"<iosPod name="GoogleSignIn" version=">=4.0.2" ...>" to
"<iosPod name="GoogleSignIn" version="& lt; 5.0.0" ...>"(without space between & and lt)

**Comment by fpbolivar** [comment]
<img width="626" alt="Screen Shot 2019-08-25 at 11 20 41 PM" src="https://user-images.githubusercontent.com/44249178/63663105-0b93d800-c78f-11e9-86af-3f8347fa09b5.png">

**Comment by fpbolivar** [comment]
unity doesn't let me build if I use '<'

**Comment by TWBestATM** [comment]
> unity doesn't let me build if I use '<'
use & lt; try again
![image](https://user-images.githubusercontent.com/15358024/63663289-614e9b80-c7f4-11e9-8b2a-6158f338b5fa.png)

they change some name in googlesiginsdk 5.0.0 so only work in less than 5.0.0 or you can just use version = "4.4.0" not add any symbol

**Comment by fpbolivar** [comment]
lol it work with those symbols thanks so much!!!

**Comment by mavc18** [comment]
omg im stuck here like all of you guys!... help meeee!

**Comment by ottolb** [comment]
We aren't stuck anymore... the solution is simple, follow the posts solutions and post here if you didn't get some specific part.

**Comment by mavc18** [comment]
I got this errors in xcode:
<img width="587" alt="Screen Shot 2019-09-01 at 1 08 19 AM" src="https://user-images.githubusercontent.com/54221617/64072516-6331b800-cc55-11e9-964f-b38baabe4fef.png">

1------
#import <GoogleSignIn/GIDSignIn.h>
@interface GoogleSignInHandler
: NSObject <GIDSignInDelegate, GIDSignInUIDelegate>

error
'Cannot find protocol declaration for 'GIDSignInUIDelegate'; did you mean 'GIDSignInDelegate'?'
2------
// Setup the Sign-In instance.
GIDSignIn *signIn = [GIDSignIn sharedInstance];
signIn.clientID = clientId;
signIn.uiDelegate = gsiHandler;
signIn.delegate = gsiHandler;

error:
'Property 'uiDelegate' not found on object of type 'GIDSignIn *'; did you mean 'delegate'?'

3--------

    Handle the auth URL
    */

    (BOOL)GoogleSignInAppController:(UIApplication *)application
    openURL:(NSURL *)url
    sourceApplication:(NSString *)sourceApplication
    annotation:(id)annotation {
    BOOL handled = [self GoogleSignInAppController:application
    openURL:url
    sourceApplication:sourceApplication
    annotation:annotation];

    return [[GIDSignIn sharedInstance] handleURL:url
    sourceApplication:sourceApplication
    annotation:annotation] ||

error:
'No visible @interface for 'GIDSignIn' declares the selector 'handleURL:sourceApplication:annotation:'

------
and to fix change this code
<img width="761" alt="Screen Shot 2019-09-01 at 1 05 40 AM" src="https://user-images.githubusercontent.com/54221617/64072478-b6efd180-cc54-11e9-82a3-0dc8b45e27ea.png">


to this code.... 
<img width="447" alt="Screen Shot 2019-09-01 at 1 09 20 AM" src="https://user-images.githubusercontent.com/54221617/64072509-38dffa80-cc55-11e9-918f-0eb3a2cad53a.png">

but still failling :(

**Comment by feemodev** [comment]
After I fixed the code,
Error disappeared when running Xcode -> Product -> build folder clean.

**Comment by lunarsugu** [comment]
After I fixed the code,
Error disappeared when running Xcode -> Product -> build folder clean.

**Comment by mavc18** [comment]
> After I fixed the code,
> Error disappeared when running Xcode -> Product -> build folder clean.

i've been build folder clean, and  then build and same error :(


------ UPDATE

Fixe the problem!!!!, i change from C#  without simbols, just '4.0.2' and works! thanks to all!

**Comment by devteamsolar** [comment]
"<iosPod name="GoogleSignIn" version="& #60; 5.0.0"  ...>"(without space between & and #60) Also works

**Comment by surbhiMagplus** [comment]
I am using direct sdk implementation not via pods and having same problem, can any one help?

> Value of type 'GIDSignIn' has no member 'uiDelegate'

Thanks in advance.

**Comment by gr9** [comment]
@surbhiMagplus me too; (hate cocoapods with the passion of 1000 burning suns) anyways; doesn't look like that property is there anymore in the new code base.  Readme.md from the 'no cocoapods' static library lead me to this repo: https://github.com/firebase/quickstart-ios 

Through which I found this code: 
That I put inside my viewDidLoad callback for my main view controller:

```
// [START setup_gid_uidelegate]
    [GIDSignIn sharedInstance].presentingViewController = self;
    [[GIDSignIn sharedInstance] signIn];
    // [END setup_gid_uidelegate]
```

Doesn't look like theres a GIDSignInUIDelegate exists anymore so I simply removed that from my protocols declared in my view controller's .h file.. I also had to add this line to the code above to get it to avoid a runtime error that was complaining about lack of client id:

`[GIDSignIn sharedInstance].clientID = @"your-client-id-defined-in-your-google-services-plist.apps.googleusercontent.com";`

**Comment by surbhiMagplus** [comment]
@gr9 I am facing another problem, My permission pop-up comes and go away I am not able to allow it. Also it is giving me google/link/?dismiss=1&is_weak_match=1 url is openURL method. Can you help me

**Comment by gr9** [comment]
@surbhiMagplus yeh me too.. getting this error in the console (obviously related to memory management somehow):

`[Warning] Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<SFAuthenticationViewController: 0x7fd9b48a2a00>)`

will let you know if i make any progress.  Seems to be related to whatever that ios alert box popping up asking for permission for the app to use google sign in; that immediately dissapears before you can tap 'ok'.

Might be iOS 13 related; I noticed the same alert box on an iOS 13 device running the older 4.1 google sign in (not firebase version); but that version of my app is still working fine re: google signin.  Wonder if there's a way to check if the app has user permission to use google sign in first & then if not first present them with the request for permission (e.g. the same way you do when requesting location permissions).

**Comment by gr9** [comment]
Only way I was able to figure this out was using cocoapods and the instructions above (e.g limit google sign on to version 4.x.)  There's something wrong obviously with the firebase 6.x build vis a vis google sign in.

**Comment by benmore99** [comment]
Just see a migration guide > https://developers.google.com/identity/sign-in/ios/quick-migration-guide

**Comment by gr9** [comment]
Thanks for the link @benmore99 ; ended up sticking with 4.x as the so called "sunsetting" of Google Analytics didn't affect GA for my apps.  Will check out your link when I eventually upgrade - at a glance I did all of that already, however it might contain something I missed.  Regardless, would be nice if the general documentation (not the more obscure and harder to find migration documentation) was correct.

**Comment by keyurdoshi18** [comment]
> Just see a migration guide > https://developers.google.com/identity/sign-in/ios/quick-migration-guide

Solved my problem.. Thanks @benmore99

**Comment by unbounded26** [comment]
I'm using Unity 2019.3.0f6 and GoogleSignIn 5.0.2 via pod, but still can't figure out the solution. I'm still stuck on the issues mentioned in [first screenshot](https://github.com/googlesamples/google-signin-unity/issues/102#issuecomment-526890133), as I just imported this plugin and change the GoogleSignIn version.

Kindly someone zip the solution or upload on git and share over here, after doing the changes.

Apologies, I'm a bit noob in the native iOS. Thanks!

**Comment by ahsan-khalil** [comment]
They have made some major changes after the **4.4.0 version** which are **incompatible with the previous version**.
And one of the significant changes is GIDSignInUIDelegate functionalities are now implemented in GIDSignInDelegate and **they have removed GIDSignInUIDelegate class.**
For more, you can read this link  **https://developers.google.com/identity/sign-in/ios/quick-migration-guide**

**Comment by renanmgs** [comment]
Actually we need to use 5.0.0+ to be in conformity with the new requisite by apple to not use UIWebView. 
But if we use 5.0.0+ we got this error, what to do?

**Comment by renanmgs** [comment]
Found a solution [here](https://github.com/googlesamples/google-signin-unity/pull/126)

**Comment by Christian254** [comment]
> > After I fixed the code,
> > Error disappeared when running Xcode -> Product -> build folder clean.
> 
> i've been build folder clean, and then build and same error :(
> 
> ------ UPDATE
> 
> Fixe the problem!!!!, i change from C# without simbols, just '4.0.2' and works! thanks to all!

I change just '4.0.2' without symbols and works too!

**Comment by alexlukens82991** [comment]
> 
> 
> @surbhiMagplus yeh me too.. getting this error in the console (obviously related to memory management somehow):
> 
> `[Warning] Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<SFAuthenticationViewController: 0x7fd9b48a2a00>)`
> 
> will let you know if i make any progress. Seems to be related to whatever that ios alert box popping up asking for permission for the app to use google sign in; that immediately dissapears before you can tap 'ok'.
> 
> Might be iOS 13 related; I noticed the same alert box on an iOS 13 device running the older 4.1 google sign in (not firebase version); but that version of my app is still working fine re: google signin. Wonder if there's a way to check if the app has user permission to use google sign in first & then if not first present them with the request for permission (e.g. the same way you do when requesting location permissions).


I am having this same issue. Did you find a solution to this?

**Comment by collectivemass** [comment]
> > unity doesn't let me build if I use '<'
> > use & lt; try again
> > ![image](https://user-images.githubusercontent.com/15358024/63663289-614e9b80-c7f4-11e9-8b2a-6158f338b5fa.png)
> 
> they change some name in googlesiginsdk 5.0.0 so only work in less than 5.0.0 or you can just use version = "4.4.0" not add any symbol

This worked like a charm for me! Thank you!

**Comment by manirana94** [comment]
Visit this link to get the best solution to resolve this.

https://stackoverflow.com/a/70984618/10635425
