### ISSUE TITLE
Error related to TextMeshPro when importing the package

### ISSUE THREAD

**Issue by aidanikuz02** [googlesamples/google-signin-unity#125]
I am using Unity 2019.3.0f3 on Windows 10. I downloaded the 1.0.4 package and imported it. During import errors appeared but then a pop up appeared that said **Resolving Android Dependencies**. Once that completed only one error remains :

Library\PackageCache\com.unity.textmeshpro@2.0.1\Scripts\Editor\TMP_PackageUtilities.cs(310,17): error CS0433: The type 'Task' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

I've tried multiple solutions. 

1. [This thread](https://forum.unity.com/threads/text-mesh-pro-dozens-of-errors-with-unity-2019-1.662575/) suggested by Unity Technologies to delete the TMP package but I'm actually using it, so not possible. 

2. Another said, its the .NET compatibility issue but I've already changed the **API Compatibility Level** to .NET 4.x at **File > Build Settings > Player Settings > Other Settings**. 

3. In [this thread](https://stackoverflow.com/questions/56422962/unity3d-the-type-task-exist-in-both-unity-tasks-and-mscorelib), the suggestions are to add the namespace declaration (tried that but the declaration didn't seem to be acceptable as it remained black instead of blue), another is to edit a file in the projects **Unity.TextMeshPro.Editor.asmdef** but this didn't change anything (I restarted unity)

**Comment by aidanikuz02** [comment]
Okay, so I fixed that error, as in it no longer appears by changing the version through **Window > Package Manager > TextMeshPro**. I updated to 1.4.1. Previously, it was 2.0.1. But when i changed that, other errors regarding Tasks appears.

**Comment by Bisher-d790** [comment]
The problem could be caused due to having two instances of Unity.Tasks.dll files in your project, you have to disable or delete one of them. Firebase adds an instance of the dll file, and might cause an issue with TextMeshPro plugin. 

You should also check the Unity Packages default folder also...
