### ISSUE TITLE
"DeveloperError" occurs when build to "Build App Bundle (Google Play)" and does not log in.

### ISSUE THREAD

**Issue by jinwook4217** [googlesamples/google-signin-unity#128]
![image](https://user-images.githubusercontent.com/23477337/75032463-04564880-54ec-11ea-9b33-ba7ba2c0d439.png)

<img width="353" alt="스크린샷 2020-02-21 오후 8 52 45" src="https://user-images.githubusercontent.com/23477337/75032923-0bca2180-54ed-11ea-9cc0-3b1dbe204e71.png">

If built with APK, Google login works well.

However, if you build into "Build App Bundle (Google Play)" for Google Play Store updates ( ~.aab ) and test it, there will be Developer Error and login will not work.

Works without a problem in iOS.

**Comment by Flappies** [comment]
Hi JungJinuk, sorry for bothering, but dit you manage to resolve this problem? I'm still battling with it and was wondering what you did to fix the problem...

**Comment by jinwook4217** [comment]
@Flappies Hi Fappies, The problem has been resolved in the following ways: #130 

What's important is that Android app signatures can be different from the launch, testing, and keystore. All app signatures must be added to the Firebase Android setting.

**Comment by dangnghia2101** [comment]
@jinwook4217 hi bro, are you resolve you problem. I have a issue like you

**Comment by ReyhanGTZ** [comment]
> @jinwook4217 hi bro, are you resolve you problem. I have a issue like you

![image](https://github.com/googlesamples/google-signin-unity/assets/79628746/67cdd3d4-a305-4994-8280-80d6eda7c961)

Just get the SHA1 Credential from App Sign In Key "Legacy" And there you go!
