### ISSUE TITLE
"DeveloperError" occurs when upload an app to google play console internal app sharing

### ISSUE THREAD

**Issue by jinwook4217** [googlesamples/google-signin-unity#130]
![image](https://user-images.githubusercontent.com/23477337/75372951-9c2bac00-58c9-11ea-843f-d7652d222786.png)

When I test an apk built in and extracted from "Unity" directly into my smartphone or run it directly on my  smartphone, there is no problem logging in to Google. However, before updating version of the app, uploading an apk to an app share inside the "Google play console" for testing and installing and testing an apk as a link causes problems with Google. ("DeveloperError")

* There is no problem with iOS.

* I have key store of my app and entered key store 
![image](https://user-images.githubusercontent.com/23477337/75373748-30e2d980-58cb-11ea-99b1-110e9b502523.png)

**Comment by HeinA** [comment]
We have the same issue.  Running a locally built apk works.  a published one gives the following error:

Exception of type 'Google.GoogleSignIn+SignInException' was thrown

We are using App Signing by Google Play 

All the applicable SHA-1 Fingerprints are registered with Firebase (and the Google Api Console)

Thanx in advance
Hein

**Comment by jinwook4217** [comment]
@HeinA 

#51 I got help here.

Did you copy the app certificate from here?

<img width="1915" alt="스크린샷 2020-03-02 오후 4 52 52" src="https://user-images.githubusercontent.com/23477337/75656377-251a5d00-5ca7-11ea-9306-02a9fb16e3bb.png">

If you want to pre-test on an internal app share, you must also add this app certificate.

<img width="983" alt="스크린샷 2020-03-02 오후 5 01 15" src="https://user-images.githubusercontent.com/23477337/75656625-ad006700-5ca7-11ea-8b0c-67c3af0bf3b9.png">

In my case, the problem was solved when I downloaded and replaced google-services.json again by copying the app certificate for internal testing and adding it to the firebase.

<img width="949" alt="스크린샷 2020-03-02 오후 5 04 06" src="https://user-images.githubusercontent.com/23477337/75656779-0b2d4a00-5ca8-11ea-88b1-c0720700550a.png">

**Comment by BlissGDev** [comment]
Happening the same to me.

I have the setup as follows:
-Android, iOS and Web keys configured.
-Added the correct SHA-1 string into the Android Key
-Added to the Unity Project the Web Id and pasted the configuration from Play Console
-Build with release keys
-Added accounts to testers on the Cloud Console Platform

I got It working on iOS (adding the GoogleServices-Info.plist and adding the client id to URL schemes) but It doesn't seem to work in Android. I keep having the same error:
DeveloperError Exception of type 'Google.GoogleSignIn+SignInException'

Any suggestion on what I might be missing ?
