### ISSUE TITLE
Android: Got Error: Error Exception of type 'Google.GoogleSignIn+SignInException' was thrown.

### ISSUE THREAD

**Issue by talhakaya** [googlesamples/google-signin-unity#137]
Other people mentioned that this SDK should have more verbose error logging, which is obvious looking at this error that says absolutely nothing:

Error Exception of type 'Google.GoogleSignIn+SignInException' was thrown.

This was "DeveloperError Exception" for a while when I put a wrong ID for web client ID. Now I have no idea. Been stuck on this issue for days.

I am using the Sample project, set up my project following the Android guide. Let me know what more info I can give you so that I could receive some advice. Thanks.

**Comment by talhakaya** [comment]
So I resolved my issue. I've got really suspicious when I created a new project and it worked fine.

Then I found that this [documentation](https://firebase.google.com/docs/auth/android/google-signin) tells me to go to the Firebase dashboard and enable Google Sign In here. Since my project had a Firebase console and my test project didn't, test one worked fine without doing this.
![image](https://user-images.githubusercontent.com/7359190/77739884-34709a00-700a-11ea-80db-d58346882c59.png)

So the documentation is there, although being quite scattered. Another thing that you might miss: putting your SHA1 key in Firebase

And if you're like me, also having to use OAuth stuff with another backend (Playfab), you might forget to put redirect URIs on your web client credentials.

Best of luck

**Comment by EdanSmith** [comment]
I'm in a similar situation... the difference is that I'm not using Firebase to authenticate my users, all I'm trying to collect is the IdToken to send to my own server, but, I'm getting that "Google.GoogleSignIn+SignInException" with no clue of what could be wrong.

**Comment by talhakaya** [comment]
I'm assuming you have RequestIdToken = true in your GoogleSignInConfiguration object, yeah?

**Comment by EdanSmith** [comment]
Yes, the problem is that task is being returned "IsFaulted" to me.

This is my little snippet:

```Csharp
        GoogleSignIn.Configuration = new GoogleSignInConfiguration
        {
            RequestIdToken = true,
            //RequestEmail = true,
            
            WebClientId = "999999999999-xxxxxxxxxxx.apps.googleusercontent.com"
        };

        Debug.Log("Set Sign In Task");

        Task<GoogleSignInUser> signIn = GoogleSignIn.DefaultInstance.SignIn();

        Debug.Log("Finish Sign In Task");
        signIn.ContinueWith(task =>
        {
// the task is faulted by now
```
I also found out that there is something that could possibly generate better logs:
```GoogleSignIn.DefaultInstance.EnableDebugLogging(true);``` but for some reason I'm not being able to make use of it :/

**Comment by zksteel** [comment]
@EdanSmith 

> I also found out that there is something that could possibly generate better logs:
GoogleSignIn.DefaultInstance.EnableDebugLogging(true); but for some reason I'm not being able to make use of it :/

Did you try to enable "Development Build" in your "Build Settings"?

But even if you manage get it work, this logs are quite useless e.q. 
`01-15 23:20:25.670 21588 21588 D SignInFragment: onActivityResult: 9009 0`
which is caused by dozen of diferent errors in Google backend.

**Comment by CarlosPerson** [comment]
> And if you're like me, also having to use OAuth stuff with another backend (Playfab), you might forget to put redirect URIs on your web client credentials.

I think this is exactly what is happening to me, and I can't seem to find documentation on what is this URI for. @talhakaya  could you please point me in the right direction?

**Comment by talhakaya** [comment]
@CarlosPerson this seems to be the most up-to-date documentation on that part of the implementation: https://docs.microsoft.com/en-us/gaming/playfab/features/authentication/platform-specific-authentication/google-sign-in-unity

It describes it for Google Play Games , although I did it with this SDK instead and was able to get it to work.

**Comment by surajsk1812** [comment]
Google Silent login is not working.

Getting below error for silent login.
**Got Error: Error Exception of type 'Google.GoogleSignIn+SignInException' was thrown.**

**Comment by daerxi** [comment]
default signin started to throw the same error. It was working last year.

**Comment by cinephile231** [comment]
> Yes, the problem is that task is being returned "IsFaulted" to me.
> 
> This is my little snippet:
> 
> ```cs
>         GoogleSignIn.Configuration = new GoogleSignInConfiguration
>         {
>             RequestIdToken = true,
>             //RequestEmail = true,
>             
>             WebClientId = "999999999999-xxxxxxxxxxx.apps.googleusercontent.com"
>         };
> 
>         Debug.Log("Set Sign In Task");
> 
>         Task<GoogleSignInUser> signIn = GoogleSignIn.DefaultInstance.SignIn();
> 
>         Debug.Log("Finish Sign In Task");
>         signIn.ContinueWith(task =>
>         {
> // the task is faulted by now
> ```
> 
> I also found out that there is something that could possibly generate better logs: `GoogleSignIn.DefaultInstance.EnableDebugLogging(true);` but for some reason I'm not being able to make use of it :/

Check if you have created SHA-1 through a keystore already in use by another project. Just in case, I created a new keystore, re-entered the SHA-1 fingerprint, and received google-services.json again... and it worked.

It's been over a year, but I'm leaving an answer in case there are people who waste time like me.

**Comment by amit3xpo** [comment]
I'm having this same issue but only after the app is published to Play Store. When ran as development build or directly from Unity with Build and run, login works fine with success but not when I install the app from Play Store. I've checked everything related to the config setup in Firebase like SHA certificate fingerprints and they are all good.

Any one facing similar issues?

**Comment by MarlonRivera** [comment]
> I'm having this same issue but only after the app is published to Play Store. When ran as development build or directly from Unity with Build and run, login works fine with success but not when I install the app from Play Store. I've checked everything related to the config setup in Firebase like SHA certificate fingerprints and they are all good.
> 
> Any one facing similar issues?

Our team faced this issue and the solution was adding both SHA-1, and SHA-256 key that appear on the google play console on the configurations section app signature. Then add this keys with your local project keys  on the firebase configuration

**Comment by hlngncy** [comment]
I am also having same issue. Its working perfectly fine on local tests which i use apk but when i upload aab to internal test it gives this error: Unity GOOGLE: Sign-in failed: Exception of type 'Google.GoogleSignIn+SignInException' was thrown.

-I am using my custom backend for keeping the user data, not firebase.
-I am using my fully configured Web OAuth Client, there was no problem when i tried sign in with GPGS even on internal test.
-Also i am using custom proguard and i am keeping all google sign in related things. But the thing is if i get my built with Release minify app crashes instantly. I am getting the error with debug minifing.
-For analytics i used Firebase. In case that its related to issue i also enabled google sign in authorization and make sure i added all sha keys.

When i get Release built, it does not shows popup at all. Otherwise, with Debug built, it shows popup, i select account and then throws this error. Do anyone has solution or ideas?
