### ISSUE TITLE
DeveloperError: Exception of type 'Google.GoogleSignIn+SignInException' was thrown

### ISSUE THREAD

**Issue by EdanSmith** [googlesamples/google-signin-unity#138]
I have been trying to implement google sign-in without the usage of Firebase.

I have downloaded the release package of google-signin-unity and tried to make its sample scene work by adding my clientId that I generated by creating an Android Oauth 2.0 on Google Console.

I have generated my own keystore and alias by using my JDK. I'm also using C# 4.0 and testing google sign-in on a Xiaomi Redmi Note 7.

I keep getting the "DeveloperError" exception and I can't find a way to gather more information on how to figure out what can be causing this exception.

All the tests are being done using a Mono build.

Steps that I have done:
1 - Create Android Oauth2 ClientID on GoogleConsole with the same package name that I have on Unity
2 - Use my generated ClientID from googleConsole on "webClientId" from SigninSampleScript
3 - Create keystore with JDK (copy and pasted its SHA-1 to google console)
4 - Load the keystore on unity build settings --> other settings
5 - Double checked the app name on "Oauth Consent Screen" from google console

This is one snippet that I have:
```Csharp
 GoogleSignIn.Configuration = new GoogleSignInConfiguration
        {
            RequestIdToken = true,          
            WebClientId = "999999-xxxxxxxx.apps.googleusercontent.com"
        };
        Task<GoogleSignInUser> signIn = GoogleSignIn.DefaultInstance.SignIn();
// signIn.Status becomes Faulted after the line above
```

I have checked these solutions #46  #51 #33 #18 but didn't have any luck.
I have also tried enabling a more verbose log, but nothing changed with this line: ```GoogleSignIn.DefaultInstance.EnableDebugLogging(true);```

Any thoughts/hint of what could be wrong on my implementation?

**Comment by EdanSmith** [comment]
After checking #35 google sign-in randomly began to work.
Important notes:
- Make sure you use a Web Client ClientID instead of an Android ClientID if `requestIdToken = true`
- Even though it may sound like you NEED Firebase for google sign-in to work (due to the excessive amount of Firebase related results when you search for "sign-in with google on unity" on google), no, you don't.

**Comment by SeveneduS** [comment]
God bless you. You saved me a lot of time.

**Comment by Fizeri** [comment]
Guys, I know the reason for this error, in short, it’s just in the inspector where you need to specify the webclientId, there you need to specify it because of this it doesn’t work, I hope I helped you, I suffered for more than 5 hours, I hope I was useful to you! I am a Russian speaker, I am traveling through a translator

**Comment by herghys** [comment]
I get my ClientID (WebClient / Oauth) from Firebase's google-service.json
