### ISSUE TITLE
Can't get google-signin to work when proguard enabled

### ISSUE THREAD

**Issue by kromley** [googlesamples/google-signin-unity#144]
Sign in was working fine until I enable Proguard. I needed to add Proguard when my dex file passed the 64k threshold. I haven't been able to set up the proguard-user.txt file correctly, and was hoping to get help in getting one that works (available for many other libraries - see https://github.com/krschultz/android-proguard-snippets/tree/master/libraries)

I have a small project that just does login, LogTest4. When Minify is set to None it runs fine, but when I set it to Proguard, I get errors as soon as I try to use GoogleSignIn. Specifically:

When it executes line:

        [DllImport(DllName)]
        static extern IntPtr GoogleSignIn_Create(IntPtr data);

I get the following error in Logcat:

2020-05-04 22:10:12.923 7196-7377/com.UARExperiences.LoginTest4 A/nces.LoginTest: java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: CallStaticVoidMethodV received NULL jclass
2020-05-04 22:10:12.923 7196-7377/com.UARExperiences.LoginTest4 A/nces.LoginTest: java_vm_ext.cc:570]     in call to CallStaticVoidMethodV
2020-05-04 22:10:12.923 7196-7377/com.UARExperiences.LoginTest4 A/nces.LoginTest: java_vm_ext.cc:570]     from boolean com.unity3d.player.UnityPlayer.nativeRender()
2020-05-04 22:10:13.003 7196-7377/com.UARExperiences.LoginTest4 A/nces.LoginTest: runtime.cc:641] Runtime aborting...

My latest proguard-user.text file has:

-dontobfuscate
-dontoptimize
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*,!code/allocation/variable

-printusage ~/Documents/usage.txt

# Preserve all native method names and the names of their classes.

-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

# Preserve the special static methods that are required in all enumeration
# classes.

-keepclassmembers,allowoptimization enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep class com.unity3d.player.UnityPlayer {
    *;
}
-keep class Google.Impl.** { *; }
-keep class Google*.** { *; }
-keep class com.unity3d.player.UnityPlayer$currentActivity { *; }
-keep class com.firebase.** { *; }

-keep class com.google.unity.** {
   *;
}
-keep public class com.google.android.gms.ads.**{
   public *;
}
-keep public class com.google.ads.**{
   public *;
}
-keepattributes *Annotation*

## https://developer.android.com/google/play-services/setup.html#Proguard ##

-keep class * extends java.util.ListResourceBundle {
    protected Object[][] getContents();
}

-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
    public static final *** NULL;
}

-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
    @com.google.android.gms.common.annotation.KeepName *;
}

-keepnames class * implements android.os.Parcelable {
    public static final ** CREATOR;
}

## -keepclassmemebernames System.Runtime.InteropServices.HandleRef
##-keep struct System.Runtime.InteropServices.HandleRef {
##    *;
##}
-keep class * implements System.Runtime.InteropServices.HandleRef { public *; }

I keep throwing things in here, but was hoping someone could help figure out what is required.

**Comment by kromley** [comment]
Fixed the problem. You need to add the following line to the proguard-user.txt file:

-keep class com.google.googlesignin.** { *; }

You also need to check the use Custom Proguard File option above Minify.

**Comment by ghost** [comment]
My man! @kromley  That was the fix. Thanks :)

**Comment by ghost** [comment]
Hi @kromley. Can you share the things that you've added in proguard file?

**Comment by kromley** [comment]
Here is what I have in my proguard file:

`

-keep class com.google.googlesignin.** { *; }
-keepnames class com.google.googlesignin.** { *; }

-keep class com.google.android.gms.auth.** { *; }


###

-keep class com.facebook.internal.* {*;}
-keep class com.facebook.* {*;}
-keep class com.facebook.unity.** {*;}
`

Hope that helps

**Comment by zkunsang** [comment]
> -keep class com.google.googlesignin.** { *; }
@kromley
 You saved my life!

**Comment by kromley** [comment]
Glad it helped.
