### ISSUE TITLE
Clarification on iOS

### ISSUE THREAD

**Issue by sskylabs** [googlesamples/google-signin-unity#149]
Context: 
I have a published app and am trying to port to iOS. However, I have encountered a few errors regarding google sign in unity package.

This is also my first time building an iOS from Xcode. 

The concern might be; with google sign in to iOS change before GoogleSignin SDK 5.0.0. I see google sign in silently has been replaced. as I have read from other issues it does not work with iOS, okay cool. Where can I change this in Xcode or Unity?

I have also read the following source extensively, but I might have missed something (I just know it). It might be that I have a problem trying to edit the code in Xcode.

- [iOS Migration Guide](https://developers.google.com/identity/sign-in/ios/quick-migration-guide)
- [Sign In for iOS](https://developers.google.com/identity/sign-in/ios/release)

I don't follow how do I know which version of GoogleSignin SDK I am in. My unity project has the latest plugin from this repository. 

Edit: Friday, June 19, 2020
I managed to get a successful build by setting the version in cocoa pods podfile to '4.0.2'. That solves the question of how to find out which version I'm using at least in Xcode, however, I'm not entirely sure how to check for unity's' version, or if that even matters.

**Comment by anisabboud** [comment]
Look for the file `GoogleSignInPlugin/Assets/GoogleSignIn/Editor/GoogleSignInDependencies.xml`:
```xml
<iosPod name="GoogleSignIn" version=">= ..."
```

Also check this PR: https://github.com/googlesamples/google-signin-unity/pull/126/files

**Comment by sskylabs** [comment]
> Look for the file `GoogleSignInPlugin/Assets/GoogleSignIn/Editor/GoogleSignInDependencies.xml`:
> 
> ```
> <iosPod name="GoogleSignIn" version=">= ..."
> ```
> 
> Also check this PR: https://github.com/googlesamples/google-signin-unity/pull/126/files

Thank you @anisabboud , much appreciated!
