### ISSUE TITLE
'GoogleSignIn/GIDSignIn.h' file not found

### ISSUE THREAD

**Issue by douglas-martins** [googlesamples/google-signin-unity#15]
Hi everyone!
I'm try to build for iOS, but Xcode give me this error. Am I missing something?
<img width="273" alt="captura de tela 2018-01-02 as 15 21 15" src="https://user-images.githubusercontent.com/13907830/34492895-9f3491dc-efd0-11e7-81f0-d8d7396acbed.png">

**Comment by Nomadjackalope** [comment]
If I am not mistaken, the following from the Readme should fix that.

> In Unity, after switching to the iOS player, make sure to run the Play Services Resolver. This will add the required frameworks and libraries to the XCode project via CocoPods.

Assets>Play Services Resolver>iOS

**Comment by douglas-martins** [comment]
Yes, and you are right, thanks! Sorry bother you

**Comment by manirana94** [comment]
Visit this link to get the best solution to resolve this.

https://stackoverflow.com/a/70984618/10635425
