### ISSUE TITLE
Crash after login in iOS version

### ISSUE THREAD

**Issue by mopsicus** [googlesamples/google-signin-unity#152]
`2020-08-06 18:57:14.746227+1000 domino[1257:427287] *** Assertion failure in +[UIAlertAction _actionWithTitle:descriptiveText:image:style:handler:shouldDismissHandler:], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3920.26.113/UIAlertAction.m:42
2020-08-06 18:57:14.759769+1000 domino[1257:427287] Uncaught exception: NSInternalInconsistencyException: Actions added to UIAlertController of style UIAlertActionStyleCancel must have a title when running in UIUserInterfaceIdiomPhone
(
	0   CoreFoundation                      0x00000001ab2d1604 409609CD-8410-38E1-BA5D-BDED609D2018 + 1222148
	1   libobjc.A.dylib                     0x00000001aaff3bcc objc_exception_throw + 56
	2   CoreFoundation                      0x00000001ab1d47bc 409609CD-8410-38E1-BA5D-BDED609D2018 + 186300
	3   Foundation                          0x00000001ab60bd1c 1A46239D-F2FC-34B6-95BC-9F38869F0C85 + 552220
	4   UIKitCore                           0x00000001ae99f5ac 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 325036
	5   UIKitCore                           0x00000001ae99f64c 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 325196
	6   UIKitCore                           0x00000001ae99f7ec 3062FF32-2182-37A2-A5F9-B38F6FB6B8C3 + 325612
	7   UnityFramework                      0x0000000106cf293c -[GIDEMMErrorHandler passcodeRequiredAlertWithCompletion:] + 556
	8   UnityFramework                      0x0000000106cf23f0 __57-[GIDEMMErrorHandler handleErrorFromResponse:completion:]_block_invoke + 724
	9   libdispatch.dylib                   0x00000001aaf969a8 5A83D0CF-8FB9-3727-8A32-012D20A47EC8 + 371112
	10  libdispatch.dylib                   0x00000001aaf97524 5A83D0CF-8FB9-3727-8A32-012D20A47EC8 + 374052
	11  libdispatch.dylib                   0x00000001aaf495b4 5A83D0CF-8FB9-3727-8A32-012D20A47EC8 + 54708
	12  CoreFoundation                      0x00000001ab24f748 409609CD-8410-38E1-BA5D-BDED609D2018 + 689992
	13  CoreFoundation                      0x00000001ab24a61c 409609CD-8410-38E1-BA5D-BDED609D2018 + 669212
	14  CoreFoundation                      0x00000001ab249c34 CFRunLoopRunSpecific + 424
	15  GraphicsServices                    0x00000001b539338c GSEventRunModal + 160
	16  UIKitCore                           0x00000001af37c22c UIApplicationMain + 1932
	17  UnityFramework                      0x0000000106971598 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 168
	18  domino                              0x00000001045cfde4 main + 76
	19  libdyld.dylib                       0x00000001ab0d1800 876FB49A-BFBA-37BF-AD37-6FFC90F7F981 + 6144
)
2020-08-06 18:57:14.760920+1000 domino[1257:427287] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Actions added to UIAlertController of style UIAlertActionStyleCancel must have a title when running in UIUserInterfaceIdiomPhone'
*** First throw call stack:
(0x1ab2d15f0 0x1aaff3bcc 0x1ab1d47bc 0x1ab60bd1c 0x1ae99f5ac 0x1ae99f64c 0x1ae99f7ec 0x106cf293c 0x106cf23f0 0x1aaf969a8 0x1aaf97524 0x1aaf495b4 0x1ab24f748 0x1ab24a61c 0x1ab249c34 0x1b539338c 0x1af37c22c 0x106971598 0x1045cfde4 0x1ab0d1800)
libc++abi.dylib: terminating with uncaught exception of type NSException`

https://prnt.sc/tuynq8

how can I fix it?

**Comment by tristangrichard** [comment]
@mopsicus How did you fix this? I am seeing this but only on iPads.

**Comment by mopsicus** [comment]
> @mopsicus How did you fix this? I am seeing this but only on iPads.

Hey, I just start using plugin for Unity, and it works
