### ISSUE TITLE
any way to exclude this from iOS? it is causing problems with UIWebView and i don't really need it on iOS

### ISSUE THREAD

**Issue by nimrodbens** [googlesamples/google-signin-unity#160]
basically the title. on iOS i use sign in with apple.

**Comment by Nyankoo** [comment]
@nimrodbens Did you solve this?

**Comment by nimrodbens** [comment]
i didn't touch this project for a long time but i think i just deleted the iOS related files from the project before compiling an APK and afterwards restoring them, that's all that i can remember.
