### ISSUE TITLE
My config file looks different than the example

### ISSUE THREAD

**Issue by EarthAdam** [googlesamples/google-signin-unity#170]
When I configure a Google API project for Android, I submit com.overview.sundial as my package name, although the config file I get back doesn't contain a package name. I just get this:
```
{
    "web":{
        "client_id":"117356081alittlebitdifferentothb6m12o3v4iovovu9.apps.googleusercontent.com",
        "project_id":"sundial-1603581112543",
        "auth_uri":"https://accounts.google.com/o/oauth2/auth",
        "token_uri":"https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
        "client_secret":"7a3XpVAnotreallythisq2mukuP86"
    }
}
```
When I run it on my phone I get the Error Callback after selecting an account to login with.
Any thoughts on why my config file is different?

**Comment by MorDeCaii** [comment]
I also was stuck with this. You have to create both types of credentials - "Web application" and "Android". Looks like you made only first one. For android you have to provide package name and SHA1 fingerprint of your app keystore.

**Comment by EarthAdam** [comment]
That's actually the config I got back from creating just the "Android" one. When I try both "Web Browser" and "Web Server", it asks for a website URL, which I don't have, so I don't even make it through that route.  
![image](https://user-images.githubusercontent.com/8453197/100471728-1fb43c80-3098-11eb-9506-555f5038f6c9.png)
I've tried a couple of times, and it auto generates a "Web Application" one as well when I made my "Android" credentials, but when I look at the configs for each of those they all look pretty similar:
![image](https://user-images.githubusercontent.com/8453197/100472249-21323480-3099-11eb-8a4d-88cd12a0a67c.png)
![image](https://user-images.githubusercontent.com/8453197/100472318-458e1100-3099-11eb-8553-5b3cec6884d2.png)

**Comment by lunargameskr** [comment]
actually, Firebase config file ( google-services.json ) looks same. I hope this can help you.

**Comment by EarthAdam** [comment]
Oh is this for Firebase? I'm hoping to access Google calendar data, not saved game data.

**Comment by lunargameskr** [comment]
I don't know why config file of example is different than current Google configure file. I guess there is version change?
I just found out Firebase's config file format is same with example.
But anyway I have another issue so there is no progress :P

**Comment by EarthAdam** [comment]
Closing this as my question was more regarding Gmail/Google Calendar OAuth, not Firebase.
