### ISSUE TITLE
Unity Cloud build fails with property 'delegate' not found on object of type 'GIDSignIn *' error.

### ISSUE THREAD

**Issue by gindemit** [googlesamples/google-signin-unity#189]
Hello,

we have since today build failures for iOS build targets.
We tried to run a build on last commit from yesterday that was successfully built and the build also failed.

The build errors from the build log:

28485: ▸ ❌;  /BUILD_PATH/soulside.app.dev-ios-release-env/dev/client/UnityClient/temp20210714-9111-je6fbm/Libraries/Plugins/iOS/GoogleSignIn/GoogleSignIn.h:18:17: no type or protocol named 'GIDSignInDelegate'
28486: ▸     : NSObject <GIDSignInDelegate>
28487: ▸ ❌;  /BUILD_PATH/soulside.app.dev-ios-release-env/dev/client/UnityClient/temp20210714-9111-je6fbm/Libraries/Plugins/iOS/GoogleSignIn/GoogleSignInAppController.mm:77:10: property 'clientID' not found on object of type 'GIDSignIn *'
28488: ▸   signIn.clientID = clientId;
28489: ▸ ❌;  /BUILD_PATH/soulside.app.dev-ios-release-env/dev/client/UnityClient/temp20210714-9111-je6fbm/Libraries/Plugins/iOS/GoogleSignIn/GoogleSignInAppController.mm:78:10: property 'delegate' not found on object of type 'GIDSignIn *'

Building with Xcode 12.4
Unity 2021.1.2f1

**Comment by tylrpage** [comment]
Use this branch if you are not already, to support 5.0.0 https://github.com/lukezbihlyj/google-signin-unity

iOS SDK updated with breaking changes in 6.0.0, change GoogleSignIn/Editor/GoogleSignInDependencies.xml, replace `>= 5.0.0` to `= 5.0.2`

https://developers.google.com/identity/sign-in/ios/release

**Comment by gindemit** [comment]
Thanks a lot for your answer. It is solved!
