### ISSUE TITLE
Force  user to login

### ISSUE THREAD

**Issue by alexArayaM** [googlesamples/google-signin-unity#190]
Hi. i am using the google sign in for unity, but i want to force the user have to log in always. on my android app i have a button to allow the users to login with google using this api, I have noted that the first time the api shows the google accounts, and that is ok, but the next time a user enter to the app, the google accounts are not showed any more. Is there a way to always shows the google accounts when the user click my button google sign in ?

any help will be greatly appreciated.

**Comment by alexArayaM** [comment]
in the GoogleSignIn.cs file i found this remark:

/// <summary>
    /// Signs out the User.
    /// </summary>
    /// <remarks>Future sign-in attempts will require the user to select the
    /// account to use when signing in.
    /// </remarks>
    public void SignOut() {
      theConfiguration = null;
      impl.SignOut();
    }


So from there i suppose the way to force a user to always select an account is to use signOut() after we are sure he was logged in without problems. I test it and it seems to work. Has somebody else test it ?

**Comment by lakshjn** [comment]
> in the GoogleSignIn.cs file i found this remark:
> 
> ///
> 
> 
> /// Signs out the User.
> ///
> 
> /// Future sign-in attempts will require the user to select the
> /// account to use when signing in.
> /// 
> public void SignOut() {
> theConfiguration = null;
> impl.SignOut();
> }
> So from there i suppose the way to force a user to always select an account is to use signOut() after we are sure he was logged in without problems. I test it and it seems to work. Has somebody else test it ?

so after trying some stuff i did that in unity coroutine, i sign out user first and the sign in it works and pop up window appears again. this is happening because google api is caching that last login info.

**Comment by alexArayaM** [comment]
@lakshjn  good to see you   made it work. I don´t know is there a way to clear the google cache, but this solution seems to work. I was debugging my android apk using visual studio, and i can see how the user data (idtoken, user name, ..) are changed after i log in. :)

**Comment by lakshjn** [comment]
@alexArayaM good to hear. So I also tried clearing that by checking out this post https://stackoverflow.com/questions/31143973/how-to-clear-googleapiclient-default-account-and-credentials
I tried 2-3 ways to clear this cache but no luck and the android plugin code seems to have the deprecated things so i left digging more.

This is the code I am using to get popups again

private IEnumerator Login()
{
       #if UNITY_ANDROID //as we dont need on the iOS
       GoogleSignIn.DefaultInstance.SignOut();
       #endif
       yield return null;
       GoogleSignIn.DefaultInstance.SignIn();
 }

**Comment by alexArayaM** [comment]
i wiil close the thread. @lakshjn thanks for the info. :)
