### ISSUE TITLE
iOS: Apple rejects archive: ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 

### ISSUE THREAD

**Issue by andrewspalato** [googlesamples/google-signin-unity#195]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 

Found this by finding all references of UIWebView in my xcode project using grep -rnw . -e 'UIWebView'.

./Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn matches

**Comment by andrewspalato** [comment]
Closing, this has been fixed in a fork of google-sign-in. Wish there was an update by google officially though

**Comment by Rainblower** [comment]
Can you give a link for fork?

**Comment by andrewspalato** [comment]
> 

Using the latest package now works. Please make sure you remove UIWebView framework in Xcode frameworks in your xcode project/workspace
