### ISSUE TITLE
Plugin overrides UnityAppController

### ISSUE THREAD

**Issue by Jyri-K** [googlesamples/google-signin-unity#2]
Thanks for a great plugin! However, it overrides UnityAppController so for example our deep links are not coming through after adding this plugin.

**Comment by stewartmiles** [comment]
@claywilkinson perhaps you could swizzle the method instead or follow what other SDKs (e.g Facbeook) are doing to chain UnityAppController?

**Comment by claywilkinson** [comment]
I'll look into - Feel free to submit a Pull Request as well.

**Comment by LeGiangAnh** [comment]
Hi,

Is there any fix for this issue? We are facing this one for iOS.

Thanks,
Anh

**Comment by claywilkinson** [comment]
Fixed this in version 1.0.2
