### ISSUE TITLE
Apple Rejection because GoogleSignIn  < 5.0.0 pod has UIWebView references

### ISSUE THREAD

**Issue by ArnauKokoro** [googlesamples/google-signin-unity#200]
Hi,

Apple is sending a rejection:
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability

```
grep -R UIWebView .
Binary file ./Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn matches
```

Is there a way to avoid that?

Thanks.

**Comment by ArnauKokoro** [comment]
I solved that using this fork: [https://github.com/lukezbihlyj/google-signin-unity](url)

**Comment by MeoMeww** [comment]
hello, i have same issue, the folk still alive ?
