### ISSUE TITLE
for iOS how should I use it now?

### ISSUE THREAD

**Issue by kadirmenz** [googlesamples/google-signin-unity#208]
Hi,
I tried to get build for iOS and this plugin scripts gives errors I will put some of thems, I found some same errors in issues and try to use their solutions but they also gives another errors so, Can someone show me which version and which scripts shall I use for iOS for make it works success?
Some errors that I get:
in default version "uiDelegate not found on object of type 'GIDSignIn *'" ,
                              No visible @interface for 'GIDSignIn' declares the selector 'handleURL:sourceApplication:annotation:', 
When I set GoogleSignIn version =>5.0.0, "~> 5.0.0" and  <5.0.0  etc.  errors-> 
I also follow some videos on youtube for example: https://www.youtube.com/watch?v=sKKbUDNOHC0

So which versions and scripts works on ios now can someone give me working versions/scripts?

**Comment by MeoMeww** [comment]
I have the same problem, it works fine at 4.4.0 But when I upload I get UIWebView error. And when I update to 6.2, I get the same error as you
