### ISSUE TITLE
Server Authentication Code

### ISSUE THREAD

**Issue by Biebras** [googlesamples/google-signin-unity#211]
Is it possible to retrieve the OAuth 2 server authentication code?

**Comment by Amrazyan** [comment]
did you find it yet

**Comment by Biebras** [comment]
I used firebase.

**Comment by Amrazyan** [comment]
You mean after getting Id token, you authorized it via firebase?

**Comment by Biebras** [comment]
Could you tell me what are you trying to do because I was trying to link google to playfabs.

**Comment by Amrazyan** [comment]
I figured it out, I was sending IdToken to my backend, and tryed to use it as accesstoken, so I needed to convert IdToken to accesstoken to make it work
