### ISSUE TITLE
Unity GoogleSignIn not worked on iOS with multiple (double) GoogleService-Info.Plist's

### ISSUE THREAD

**Issue by Daniil-Mozolevskiy** [googlesamples/google-signin-unity#223]
In my Unity project, i use multiple Firebase projects, first - for database and remote config, second - for firebase auth.
In my auth logic, i use google sign in and apple sign in. 
When i start and play game on Android, it's work correctly, but on iOS, when i click on goole login button, google sign in shows native popup, and if you select google mail account, native popup will hide and then nothing will happen.
I tested it with one GoogleService-Info.Plits and it's work fine, but when a add the second GoggleService-Info.Plist, it's not worked for me.

`SignInException: Exception of type 'Google.GoogleSignIn+SignInException' was thrown.`

**Comment by CodeMasterYi** [comment]
https://github.com/googlesamples/google-signin-unity/pull/205 @Daniil-Mozolevskiy
