### ISSUE TITLE
Error with task conflict right after installation in clean project.

### ISSUE THREAD

**Issue by diviatrix** [googlesamples/google-signin-unity#226]
Library\PackageCache\com.unity.visualscripting@1.7.8\Editor\VisualScripting.Core\Utilities\EditorLinqUtility.cs(18,81): error CS0433: The type 'CancellationToken' exists in both 'Unity.Tasks, Version=0.0.0.0,

unity 2021.3.16f1

**Comment by ArkTarusov** [comment]
Hello. 
You should simply delete the "Parse" folder that comes with this plugin.
The plugin has not been updated for a very long time. In new versions of the Unity, the "Parse" library is already included in other unity plugins.

**Comment by diviatrix** [comment]
Thank you, it worked!
