### ISSUE TITLE
The SHA-1 you specified is already used with the same package name for a different Android OAuth2 client.

### ISSUE THREAD

**Issue by truonguit2010** [googlesamples/google-signin-unity#3]
Hi,

I used Google Play Game Service before in my game. Now I want to change to Google Sign-In. But I cannot get the configuration file. Is there any way to get it? 

Thank you.

**Comment by claywilkinson** [comment]
If you go to the Play console and in the Game Sevices tab, select your game.  At the top of the Game Details page there should be a button "Add Firebase"  That should link the your application to all the dashboards.

**Comment by jinyneu** [comment]
oh I got the same problem, do you have any solution?

**Comment by erperejildo** [comment]
what was the solution?
