### ISSUE TITLE
Return Email always null

### ISSUE THREAD

**Issue by GePrasetyo** [googlesamples/google-signin-unity#38]
I can get displayname, photo, id. But email return always null. here is my code

				data[0] = task.Result.Email;
				data[1] = task.Result.UserId;
				data[2] = task.Result.DisplayName;
				data[3] = task.Result.ImageUrl.ToString();

				print("my data google: " +data[0] +"," +data[1]+"," +data[2]+".");
				print("link photo : " +data[3]);;

**Comment by pronaypeddiraju** [comment]
Getting the same error

task.Result.Email is always null for android but seems to be working for iOS

**Comment by GePrasetyo** [comment]
Hi @pronaypeddiraju 

I've manage this issue. have you set request email = true ?

i put this code when trying to login

GoogleSignIn.Configuration.RequestEmail = true;

**Comment by pronaypeddiraju** [comment]
Thanks @GePrasetyo . It worked once I added the RequestEmail = true.

**Comment by KTSOEV** [comment]
Thanks you!
