### ISSUE TITLE
I always log in automatically after logging out.

### ISSUE THREAD

**Issue by doyongid** [googlesamples/google-signin-unity#40]
I sign in automatically after SignOut () or Disconnect ().
I am logged in automatically after uninstalling and reinstalling the app.

How do I open a pop-up window to select one of my accounts?

Thank you.

configuration = new GoogleSignInConfiguration {
                WebClientId = GOOGLE_WEB_ID,
                ForceTokenRefresh = true,
                RequestAuthCode = true
            };

**Comment by doyongid** [comment]
You can register more than one account on Safari.

**Comment by unbounded26** [comment]
How you solved this issue?

**Comment by minhlong2605** [comment]
hello, did you find solution? i'm stuck :((

**Comment by doyongid** [comment]
> hello, did you find solution? i'm stuck :((
It seems to depend on the settings of the web browser.
After logging out of all Google accounts from your web browser, try again and a pop-up window will appear.
