### ISSUE TITLE
Get Access Token "Malformed" Error

### ISSUE THREAD

**Issue by timnlupo** [googlesamples/google-signin-unity#64]
Hi everyone,

I am trying to authenticate my app to make REST calls to Google from Unity. I successfully generate an `authCode` from logging in with this API with the following configuration.
```
configuration = new GoogleSignInConfiguration {
	WebClientId = webClientId,
	UseGameSignIn = false,
	RequestIdToken = true,
	RequestAuthCode = true,
	AdditionalScopes = scopes
};
```
I'm now trying to exchange my `authCode` for an `accessToken` so I can make REST calls to different APIs. I referenced #57 and my code for this is below.
```
WWWForm formData = new WWWForm();
formData.AddField("client_id", webClientId);
formData.AddField("client_secret", webClientSecret);
formData.AddField("grant_type", "authorization_code");
formData.AddField("code", "AuthCode");

UnityWebRequest www = UnityWebRequest.Post("https://www.googleapis.com/oauth2/v4/token", formData);
```
I get a `400 Generic/unknown HTTP error` with the response `{ "error": "invalid_grant", "error_description": "Malformed auth code." }`. What is going wrong? Am I able to use a `webClientID` to access Google API from REST? Is there a problem with `authCode` generation? Please advise, thanks.

**Comment by timnlupo** [comment]
I hate myself. I've been debugging for like 5 hours. In the line `formData.AddField("code", "AuthCode");` I put `"` around `AuthCode`. I wasn't sending my actual variable lol, it's all fixed now.

**Comment by vlon** [comment]
Hi, How is authcode generated, I am stuck here
