### ISSUE TITLE
Already Logged in?

### ISSUE THREAD

**Issue by programmermattsrum** [googlesamples/google-signin-unity#67]
Is there a way to see if you are already logged into google with this plugin?  I have searched everywhere and can't seem to find a way.

**Comment by thientvimo** [comment]
see I have the same problem

**Comment by thientvimo** [comment]
this is error I
SignInException: DefaultInstance already created.  Cannot change configuration after creation.
      at Google.GoogleSignIn.set_Configuration

then you can add this code when create new google Configuration, that fixed my issue
if(GoogleSignIn.Configuration == null)
        {
            GoogleSignIn.Configuration = configuration;
            GoogleSignIn.Configuration.UseGameSignIn = false;
        }
