### ISSUE TITLE
App crash on launch - Unable to use Google Ads with Google Sign unity packages

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [googlesamples/google-signin-unity#69]
I am able to both plugins individually but not together 
Getting this error on lauch : 

>  W ActivityManager:   Force finishing activity com.xyz.abc/com.unity3d.player.UnityPlayerActivity

.
I found this warning while resolving dependencies .

Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
com.google.android.gms:play-services-auth:16+ --> com.google.android.gms:play-services-auth:+.
I have posted same issue here . 
 [https://github.com/googleads/googleads-mobile-unity/issues/802](url)

**Comment by FaiyazMdAbdul** [comment]
i used invalid App ID .. Oops.

**Comment by FaizanDurrani** [comment]
> i used invalid App ID .. Oops.

Could you give more details on how you fixed this? I am currently facing the same issue (I think)

The app crashes as soon as I do GoogleSignIn.DefaultInstance It started happening after I upgraded to 1.0.4 from 1.0.2
