### ISSUE TITLE
Android Crashes @ Firebase.Auth.GoogleAuthProvider.GetCredential

### ISSUE THREAD

**Issue by mygreymatter** [googlesamples/google-signin-unity#87]
The full code is [GameController.txt](https://github.com/googlesamples/google-signin-unity/files/3097969/GameController.txt)
Hi,
Google SignIn was successful. The IdToken was received. when the token was passed to

`Credential credential = Firebase.Auth.GoogleAuthProvider.GetCredential(((Task<GoogleSignInUser>)task).Result.IdToken, "");`
, the app is crashed without any trace or log.

**Comment by mygreymatter** [comment]
I found out the issue. The DefaultInstance must be called before calling for credential.
`FirebaseAuth auth = FirebaseAuth.DefaultInstance;`

**Comment by dadobtx** [comment]
> I found out the issue. The DefaultInstance must be called before calling for credential.
> `FirebaseAuth auth = FirebaseAuth.DefaultInstance;`

Hi @mygreymatter . It solved the issue that the app closes and resumes again. But It still doesn't register in firebase console.  
The app works well and sign in function works until GetCredential. The whole data user like name, mail, and google Id token are shown but the message Sign in successful never appears. 
Please could you share with me if you solved the whole sign-in issue

**Comment by matej1231** [comment]
@dadobtx Did you resolve that issue? I have the same issue here in Unity 2021.3.2f1, it just won't pass that line of code, and before that I had crash like you did until adding `FirebaseAuth auth = FirebaseAuth.DefaultInstance;`

**Comment by dadobtx** [comment]
> @dadobtx Did you resolve that issue? I have the same issue here in Unity 2021.3.2f1, it just won't pass that line of code, and before that I had crash like you did until adding `FirebaseAuth auth = FirebaseAuth.DefaultInhstance;`

Hello @matej1231 I followed this tutorial https://youtu.be/0jwVkFVaPBY that worked for me. Just make sure that you are using the last updated firebase unity package version.
