### ISSUE TITLE
Errors when opening in Unity 2019.1.0f2

### ISSUE THREAD

**Issue by dan-o3h** [googlesamples/google-signin-unity#88]
Looks like libraries / namespaces have moved around:

Assets/SignInSample/SigninSampleScript.cs(61,44): error CS0433: The type 'Task<T>' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by dan-o3h** [comment]
Managed to fix by going to Parse > Plugins > Unity.Tasks  and in the inspector > Exclude Platforms  and checked Editor.

**Comment by IneOtherGuys** [comment]
You can just delete the Parse folder altogether (worked for me in Unity 2018.1.3), I think it fixed compatibility issues with older versions of Unity.

**Comment by stewartmiles** [comment]
If you're using .NET 4.x you'll need to import the plugins from the `dotnet4` directory. 

@IneOtherGuys the Parse folder is required as we have references from Firebase DLLs to the Parse DLLs, there are type forwarding DLLs in the Parse/dotnet4 folder that are needed to forward type definitions to the .NET framework's Task classes.

**Comment by michelleran** [comment]
Encountering the same error - OP's solution gets rid of it, but I'd like to run the sample in the editor if possible. @stewartmiles I'm a bit confused since I don't see a `dotnet4` directory - how can we resolve this error without excluding the editor? Thanks in advance!
