### ISSUE TITLE
All version but the 1st release is missing google signin .aar file.

### ISSUE THREAD

**Issue by Smileynator** [googlesamples/google-signin-unity#9]

**Comment by dgates** [comment]
Just wondering, were you able to fix/work around this? I think I may be having the same issue...

**Comment by claywilkinson** [comment]
The google-signin-support aar is definitely included in the 1.0.2 release of the unitypackage. It is renamed *.srcaar to prevent Unity from including the arm and the x86 libraries when building a non-fat apk.
